spring:
  application:
    name: SERVICE-REGISTRY

server:
  port: 8761

eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false