server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include=gateway:


spring:
  application:
    name: API-GATEWAY
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendB
                fallbackUri: forward:/fallback/testService
                statusCodes:
                  - 500
#            - CircuitBreaker=backendB
#            - RewritePath=/fallback/testService/(?<path>.*), /$\{path}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      enabled: true
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging.level.io.github.resilience4j: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 200ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    backendA:
      baseConfig: default
    backendB:
      slidingWindowSize: 2
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordFailurePredicate: com.bench.practice.cloud.gateway.HttpInternalServicePredicate
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.net.ConnectException
      ignoreExceptions:
        - java.lang.IllegalStateException

resilience4j.timelimiter:
  time-limiter-aspect-order: 398
  configs:
    default:
      timeoutDuration: 1s
      cancelRunningFuture: false
  instances:
    backendB:
      timeoutDuration: 250ms