spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 8080


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      enabled: true
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
