version: '2'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    environment:
      - 'VAULT_ADDR=http://localhost:8200'
    volumes:
      - D:\docker\vault\volumes\logs:/vault/logs
      - D:\docker\vault\volumes\file:/vault/file
      - D:\docker\vault\volumes\config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
