eureka:
    instance:
        instance-id: ${spring.application.name}-${random.uuid}
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters: TokenRelay
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: product-service
                predicates:
                - Path=/api/product
                uri: lb://product-service
            -   id: order-service
                predicates:
                - Path=/api/order
                uri: lb://order-service
        loadbalancer:
            ribbon:
                enabled: false
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        issuer-uri: ${KEYCLOAK_URI:http://localhost:8180/auth/realms/microservices-realm}
                registration:
                    spring-cloud-gateway-client:
                        authorization-grant-type: authorization_code
                        client-id: spring-cloud-gateway-client
                        client-secret: f2939f34-418b-40cc-a75c-527eb64f8d6c
                        provider: keycloak
                        redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8180/auth/realms/microservices-realm/protocol/openid-connect/certs
